### ISSUE TITLE
简单介绍reStructedText语法？

### ISSUE THREAD

**Issue by modi** [sfcn/docs#6]

**Comment by Rivsen** [comment]
http://www.ibm.com/developerworks/cn/opensource/os-sphinx-documentation/ 这里有一篇，我开始是看它入门的

**Comment by chrisyue** [comment]
@Rivsen  :+1: 谢谢提供转送门

**Comment by chrisyue** [comment]
https://github.com/sfcn/symfony-docs-chs/commit/ae31cd336435c47a2e476da5909ee3222d33ab15 @modi 介绍已经翻译完毕，可以关闭了？
